name: release

on:
  workflow_dispatch:

jobs:
  release:
    if: github.repository == 'philiplehmann/docker-hub-retention'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: "0"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - run: bun install

      - name: configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run release
