name: test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          yarn install
      - run: |
          yarn release:build
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: docker hub retention
        id: registry 
        uses: ./
        with:
          repository: "philiplehmann/puppeteer" # required, repository name
          dryrun: "true" # optional, default is false
          match: "([0-9\\.]+)-([0-9]+)" # optional
          retention: "7d" # optional, default is 30d

