name: typecheck

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: yarn install
      - run: yarn tsc --noEmit
